//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.WSZW.data;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import com.googlecode.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.BooleanPrefField;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class InfoFile_
    extends SharedPreferencesHelper
{


    public InfoFile_(Context context) {
        super(PreferenceManager.getDefaultSharedPreferences(context));
    }

    public InfoFile_.InfoFileEditor_ edit() {
        return new InfoFile_.InfoFileEditor_(getSharedPreferences());
    }

    public StringPrefField ZTYWkaishishijian() {
        return stringField("ZTYWkaishishijian", "");
    }

    public StringPrefField ZTYWyuanyin() {
        return stringField("ZTYWyuanyin", "");
    }

    public StringPrefField banjieriqi() {
        return stringField("banjieriqi", "");
    }

    public StringPrefField baselist_yewuliushuihao() {
        return stringField("baselist_yewuliushuihao", "");
    }

    public StringPrefField bdlr_ywlsh() {
        return stringField("bdlr_ywlsh", "");
    }

    public StringPrefField bizArchivesId() {
        return stringField("bizArchivesId", "");
    }

    public StringPrefField bz_msg() {
        return stringField("bz_msg", "");
    }

    public StringPrefField bz_slczy() {
        return stringField("bz_slczy", "");
    }

    public StringPrefField bz_sqr_phone() {
        return stringField("bz_sqr_phone", "");
    }

    public StringPrefField bz_yy() {
        return stringField("bz_yy", "");
    }

    public StringPrefField chanDocId() {
        return stringField("chanDocId", "");
    }

    public StringPrefField chanIds() {
        return stringField("chanIds", "");
    }

    public StringPrefField content() {
        return stringField("content", "");
    }

    public StringPrefField deliverTime() {
        return stringField("deliverTime", "");
    }

    public StringPrefField dfflb_bjzt() {
        return stringField("dfflb_bjzt", "");
    }

    public StringPrefField dxtz_beizhu() {
        return stringField("dxtz_beizhu", "");
    }

    public StringPrefField dxtz_shibaiyuanyin() {
        return stringField("dxtz_shibaiyuanyin", "");
    }

    public StringPrefField edittext_1_zwfw_search() {
        return stringField("edittext_1_zwfw_search", "");
    }

    public StringPrefField edittext_2_zwfw_search() {
        return stringField("edittext_2_zwfw_search", "");
    }

    public StringPrefField gzlm_title() {
        return stringField("gzlm_title", "");
    }

    public StringPrefField gzlm_url() {
        return stringField("gzlm_url", "");
    }

    public StringPrefField id() {
        return stringField("id", "");
    }

    public StringPrefField infoCookie() {
        return stringField("infoCookie", "");
    }

    public StringPrefField infoUserId() {
        return stringField("infoUserId", "");
    }

    public StringPrefField infoUsername() {
        return stringField("infoUsername", "");
    }

    public BooleanPrefField isAutoLogin() {
        return booleanField("isAutoLogin", false);
    }

    public StringPrefField jgff_yewuliushuihao() {
        return stringField("jgff_yewuliushuihao", "");
    }

    public StringPrefField lettertypeName() {
        return stringField("lettertypeName", "");
    }

    public StringPrefField organId() {
        return stringField("organId", "");
    }

    public StringPrefField postinfoid() {
        return stringField("postinfoid", "");
    }

    public StringPrefField postinfoname() {
        return stringField("postinfoname", "");
    }

    public StringPrefField postinfotype() {
        return stringField("postinfotype", "");
    }

    public StringPrefField prefixURL() {
        return stringField("prefixURL", "");
    }

    public StringPrefField replyContent() {
        return stringField("replyContent", "");
    }

    public StringPrefField replyTimeString() {
        return stringField("replyTimeString", "");
    }

    public StringPrefField result() {
        return stringField("result", "");
    }

    public StringPrefField score() {
        return stringField("score", "");
    }

    public StringPrefField searchNo() {
        return stringField("searchNo", "");
    }

    public StringPrefField serviceSubjectId() {
        return stringField("serviceSubjectId", "");
    }

    public StringPrefField serviceSubjectName() {
        return stringField("serviceSubjectName", "");
    }

    public StringPrefField shengqingrenCardId() {
        return stringField("shengqingrenCardId", "");
    }

    public StringPrefField shengqingrenname() {
        return stringField("shengqingrenname", "");
    }

    public StringPrefField shengqingriqi() {
        return stringField("shengqingriqi", "");
    }

    public StringPrefField shixiang_id() {
        return stringField("shixiang_id", "");
    }

    public StringPrefField shixiang_name() {
        return stringField("shixiang_name", "");
    }

    public StringPrefField summary() {
        return stringField("summary", "");
    }

    public StringPrefField title() {
        return stringField("title", "");
    }

    public StringPrefField urlCenterWs() {
        return stringField("urlCenterWs", "");
    }

    public StringPrefField writeTime() {
        return stringField("writeTime", "");
    }

    public StringPrefField wssq_wsyslh() {
        return stringField("wssq_wsyslh", "");
    }

    public StringPrefField xzzq_num() {
        return stringField("xzzq_num", "");
    }

    public StringPrefField yslyw_shengqingrenCardId() {
        return stringField("yslyw_shengqingrenCardId", "");
    }

    public StringPrefField zhutiID() {
        return stringField("zhutiID", "");
    }

    public StringPrefField zhutiName() {
        return stringField("zhutiName", "");
    }

    public StringPrefField zwgk_url() {
        return stringField("zwgk_url", "");
    }

    public final static class InfoFileEditor_
        extends EditorHelper<InfoFile_.InfoFileEditor_>
    {


        InfoFileEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> ZTYWkaishishijian() {
            return stringField("ZTYWkaishishijian");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> ZTYWyuanyin() {
            return stringField("ZTYWyuanyin");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> banjieriqi() {
            return stringField("banjieriqi");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> baselist_yewuliushuihao() {
            return stringField("baselist_yewuliushuihao");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bdlr_ywlsh() {
            return stringField("bdlr_ywlsh");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bizArchivesId() {
            return stringField("bizArchivesId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bz_msg() {
            return stringField("bz_msg");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bz_slczy() {
            return stringField("bz_slczy");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bz_sqr_phone() {
            return stringField("bz_sqr_phone");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> bz_yy() {
            return stringField("bz_yy");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> chanDocId() {
            return stringField("chanDocId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> chanIds() {
            return stringField("chanIds");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> content() {
            return stringField("content");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> deliverTime() {
            return stringField("deliverTime");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> dfflb_bjzt() {
            return stringField("dfflb_bjzt");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> dxtz_beizhu() {
            return stringField("dxtz_beizhu");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> dxtz_shibaiyuanyin() {
            return stringField("dxtz_shibaiyuanyin");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> edittext_1_zwfw_search() {
            return stringField("edittext_1_zwfw_search");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> edittext_2_zwfw_search() {
            return stringField("edittext_2_zwfw_search");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> gzlm_title() {
            return stringField("gzlm_title");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> gzlm_url() {
            return stringField("gzlm_url");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> id() {
            return stringField("id");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoCookie() {
            return stringField("infoCookie");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoUserId() {
            return stringField("infoUserId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> infoUsername() {
            return stringField("infoUsername");
        }

        public BooleanPrefEditorField<InfoFile_.InfoFileEditor_> isAutoLogin() {
            return booleanField("isAutoLogin");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> jgff_yewuliushuihao() {
            return stringField("jgff_yewuliushuihao");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> lettertypeName() {
            return stringField("lettertypeName");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> organId() {
            return stringField("organId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> postinfoid() {
            return stringField("postinfoid");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> postinfoname() {
            return stringField("postinfoname");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> postinfotype() {
            return stringField("postinfotype");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> prefixURL() {
            return stringField("prefixURL");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> replyContent() {
            return stringField("replyContent");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> replyTimeString() {
            return stringField("replyTimeString");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> result() {
            return stringField("result");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> score() {
            return stringField("score");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> searchNo() {
            return stringField("searchNo");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> serviceSubjectId() {
            return stringField("serviceSubjectId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> serviceSubjectName() {
            return stringField("serviceSubjectName");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> shengqingrenCardId() {
            return stringField("shengqingrenCardId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> shengqingrenname() {
            return stringField("shengqingrenname");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> shengqingriqi() {
            return stringField("shengqingriqi");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> shixiang_id() {
            return stringField("shixiang_id");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> shixiang_name() {
            return stringField("shixiang_name");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> summary() {
            return stringField("summary");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> title() {
            return stringField("title");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> urlCenterWs() {
            return stringField("urlCenterWs");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> writeTime() {
            return stringField("writeTime");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> wssq_wsyslh() {
            return stringField("wssq_wsyslh");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> xzzq_num() {
            return stringField("xzzq_num");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> yslyw_shengqingrenCardId() {
            return stringField("yslyw_shengqingrenCardId");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> zhutiID() {
            return stringField("zhutiID");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> zhutiName() {
            return stringField("zhutiName");
        }

        public StringPrefEditorField<InfoFile_.InfoFileEditor_> zwgk_url() {
            return stringField("zwgk_url");
        }

    }

}
