//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.WSZW.Activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.WSZW.Activity.R.id;
import com.WSZW.Activity.R.layout;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class Sjsl_Sjdj_Deny_Activity_
    extends Sjsl_Sjdj_Deny_Activity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.layout_sjsl_sjdj_deny);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        tvTitle_two_Name = ((TextView) findViewById(id.tvTitle_two_Name));
        tvInfo = ((TextView) findViewById(id.tvInfo));
        lv_bltj_fuhe = ((ListView) findViewById(id.lv_bltj_fuhe));
        rl_title = ((RelativeLayout) findViewById(id.rl_title));
        btn_sjdj_next = ((Button) findViewById(id.btn_sjdj_next));
        btn_cancel = ((Button) findViewById(id.btn_cancel));
        lv_tjcl_fuhe = ((ListView) findViewById(id.lv_tjcl_fuhe));
        tv_name = ((TextView) findViewById(id.tv_name));
        initView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static Sjsl_Sjdj_Deny_Activity_.IntentBuilder_ intent(Context context) {
        return new Sjsl_Sjdj_Deny_Activity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, Sjsl_Sjdj_Deny_Activity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public Sjsl_Sjdj_Deny_Activity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
